version: 2.1

orbs:
  android: circleci/android@2.4.0
  flutter: circleci/flutter@2.0.2

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default 
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.19.1
      - run:
          name: Flutter pub get
          command: |
            flutter pub get
      - run:
          name: Build APK
          command: |
            flutter build apk
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk